config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'places#index'
  resources :places do
    resources :photos, :comments, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email
  validates :message, presence: true
  validates :rating, presence: true

  RATINGS = {
    'one star': '1_star',
    'two stars': '2_stars',
    'three stars': '3_stars',
    'four stars': '4_stars',
    'five stars': '5_stars'
  }
  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver_now
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :place
  validates :picture, presence: true
  validates :caption, presence: true, length: { maximum: 200 }
  mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :photos
  geocoded_by :address
  after_validation :geocode
  validates :name, presence: true, length: { in: 3..100 } 
  validates :address, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :places
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    comment = @place.comments.create(comment_params.merge(user: current_user))
    if comment.valid?
      redirect_to place_path(@place)
    else
      render plain: 'The information you entered is invalid', status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
before_action :authenticate_user!, only: [:new, :create, :edit]

  def new
    @photo = Photo.new
  end

  def create 
    @place = Place.find(params[:place_id])
    @photo = @place.photos.create(photo_params)
    if @photo.valid?
      redirect_to place_path(@place)
    else
      render plain: 'The information you entered is invalid', status: :unprocessable_entity
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :picture)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
  def index
    @places = Place.paginate(page: params[:page], per_page: 8)
  end
  
  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
  end

  def update
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
    @place.destroy
    redirect_to root_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'Nomster', root_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_place_path, class: 'nav-link' do %>
            <i class="fa fa-plus-circle"></i>
            New Place
          <% end %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br>
    <%= f.submit :Create, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag 'birdscropped.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>Birds</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'chinesecropped.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>Chinese restaurant</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'fancycropped.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>Fancy restaurant</h3>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<br>
<br>
<div class="container">
  <div class="row">
    <% @places.each do |place| %>
      <div class="col-12 col-lg-6">
        <div class="booyah-box">
          <h1><%= link_to place.name, place_path(place) %></h1><br>
          <i><%= place.address %></i><br><br>
          <p><%= place.description %></p><br>
          <% if place.photos.present? %>
            <div><%= image_tag place.photos.last.picture.url.to_s, class: "img-fluid" %></div><br>
          <% end %>
          <% if place.user.present? %>
            <small><%= place.user.email %></small>
          <% end %>
          <% if place.comments.present? %>
            <div class="col-12">
              <blockquote>
                <% if place.comments.last.humanized_rating.present? %>
                  <b><%= place.comments.last.humanized_rating %></b>
                <% end %>
                <br>
                <%= place.comments.last.message %>
                <small><%= place.comments.last.user.email %></small>
              </blockquote>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="paginate-links">
  <div class="paginate-links-child">
    <%= will_paginate(@places, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
</div>

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br>
    <%= f.submit :Create %>
  <% end %>
</div>

app/views/places/show.html.erb
<br>
<hr class="style1">
<h1 class="text-center"><%= @place.name %></h1>
<hr class="style1">
<br>
<div id="show-container" class="container">
  <div class="row">  
    <div class="booyah-box col-sm-10 col-lg-5 offset-sm-1">
      <i><%= @place.address %></i>
      <hr>
      <p><%= @place.description %></p>
      <hr>
      <p><%= @place.user.email %></p>
      <br>
      <% if @place.latitude.present? && @place.longitude.present? %>
        <script>

          function initMap() {
            var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

            var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 12,
              center: myLatLng
            });

            var marker = new google.maps.Marker({
              position: myLatLng,
              map: map,
              title: 'Hello World!'
            });
          }
        </script>
      <% end %>
        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAe-cbeggfx9doD9g3mk-NcHT3Z7z88BFg&callback=initMap">
        </script>
      <div id="map"></div>
      <br>
      <div>
        <% if current_user && current_user == @place.user %>
          <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
          <!-- Button trigger image modal -->
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal2">
            Add an Image
          </button>
          <%= link_to 'Destroy', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'btn btn-danger' %>
        <% end %>
        <br><br>
      </div>
    </div>
    <div class="col-10 offset-1 col-lg-5 offset-lg-0">
      <br>
      <div>
        <h1 class="float-left">Comments</h1>
        <button type="button" class="btn btn-primary btn-lg float-right" data-toggle="modal" data-target="#myModal">
            Add a comment
        </button>
      </div>
      <div class="clear"></div>
      <br>
      <div id="comments-box">
        <% @place.comments.each do |comment| %>
          <blockquote>
            <% if comment.humanized_rating.present? %>
              <b><%= comment.humanized_rating %></b>
            <% end %>
            <br>
            <%= comment.message %>
            <br>
            <small><%= comment.user.email %></small>
          </blockquote>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br>
<% if @place.photos.present? %>
  <div class="row">
    <a id="dropdown-button" class="button default ok btn btn-outline-info offset-5" href="#img-dropdown" data-toggle="collapse" aria-expanded="false">
      View Images
    </a>
  </div>
<% end %>
<br>
<div id="img-dropdown" class="collapse booyah-box col-10 offset-1">
<% @place.photos.each do |photo| %>
  <%= image_tag photo.picture.url.to_s, class: "img-fluid" %>
  <p><%= photo.caption %></p>
<% end %>
</div>
<div class="clear"></div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
      </div>
      <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :message %>
          <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add an Image</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
          <%= f.input :caption %>
          <%= f.input :picture %>
          <div class="modal-footer">
          <%= f.submit "Add a Photo", class: 'btn btn-primary' %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br>



app/views/users/show.html.erb
<div class="booyah-box col-md-10 offset-md-1">
  <div class="row">
    <div class="col-sm-4">
      <%= image_tag 'user4hd.png', class: 'profile-img img-fluid' %>
     </div> 
    <div class="col-sm-8 user-info">
      <p><%= @user.email %></p>
      <hr>
      <p>Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></p>
      <hr>
      <p><%= @user.comments.count %> total comments</p>
      <p><%= @user.comments.where(rating: '5_stars').count %> total 5 star reviews</p>
    </div>
  </div>
  <div class="clear"></div>
</div>
<br><br>
<h1 class="text-center">My Comments</h1>
<br><br>
<div class="row">
  <% @user.comments.each do |comment| %>
    <div class="col-12 col-sm-6">
      <div class=" booyah-box col-md-10 offset-md-1">
        <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h2>
        <blockquote>
          <% if comment.humanized_rating.present? %>
            <b><%= comment.humanized_rating %></b>
          <% end %>
          <br>
          <%= comment.message %>
          <br>
          <small><%= comment.user.email %></small>
        </blockquote>
      </div>
    </div>
  <% end %>
</div>
<div class="clear"></div>
<br><br>
<h2 class="text-center">My Places</h2>
<br><br>
<div class="row">
  <% @user.places.each do |place| %>
    <div class=" col-12 col-sm-6">
      <div class="booyah-box col-md-10 offset-md-1">
        <h1><%= link_to place.name, place_path(place) %></h1><br>
        <i><%= place.address %></i><br><br>
        <p><%= place.description %></p><br>
        <% if place.photos.present? %>
          <div><%= image_tag place.photos.last.picture.url.to_s, class: "img-fluid" %></div><br>
        <% end %>
        <% if place.user.present? %>
          <small><%= place.user.email %></small>
        <% end %>
        <% if place.comments.present? %>
          <div class="col-12">
            <blockquote>
              <% if place.comments.last.humanized_rating.present? %>
                <b><%= place.comments.last.humanized_rating %></b>
              <% end %>
              <br>
              <%= place.comments.last.message %>
              <small><%= place.comments.last.user.email %></small>
            </blockquote>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>